stages:
  - build
  - deploy-dev
  - deploy

#variables:
#  COMPOSE_DOCKER_CLI_BUILD: 1
#  DOCKER_BUILDKIT: 1

# before_script:
#   - docker login -u $NEXUS_REGISTRY_USER -p $NEXUS_REGISTRY_PASSWD registry.mplab.io

build:telegramm_ai_service:
  #allow_failure: true
  stage: build
  image:
    name: docker:stable
    entrypoint: ["/bin/sh", "-c"]
  tags: [infra]
  only:
    - main
  variables:
    CONTAINER_IMAGE: registry.dplab.tech/telegramm_ai_service:${CI_COMMIT_SHORT_SHA}
    CONTAINER_IMAGE_LATEST: registry.dplab.tech/telegramm_ai_service:latest
  script:
    - docker build -f Dockerfile -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE_LATEST}

deploy:
  stage: deploy
  image:
    name: docker:latest
    entrypoint: ["/bin/sh", "-c"]
  when: manual
  tags: [app-ea]
  variables:
    CONTAINER_IMAGE_DEVTEST: registry.dplab.tech/telegramm_ai_service:latest
  # before_script:
  #   - docker login -u $NEXUS_REGISTRY_USER -p $NEXUS_REGISTRY_PASSWD registry.mplab.io
  script:
    - docker compose -f docker-compose.yaml -p telegramm_ai_service down --timeout 10
    - docker compose -f docker-compose.yaml  pull telegramm_ai_service
    - docker compose -f docker-compose.yaml -p telegramm_ai_service up -d

deploy_dev:
  stage: deploy
  tags: [eliment-dev]
  only:
    - main
  image:
    name: docker/compose
    entrypoint: ["/bin/sh", "-c"]
  script:
    - IMAGE_TAG=latest docker compose -f docker-compose-dev.yml -p telegramm_ai_service down --timeout 10
    - IMAGE_TAG=latest docker compose -f docker-compose-dev.yml  pull telegramm_ai_service
    - IMAGE_TAG=latest docker compose -f docker-compose-dev.yml  up -d telegramm_ai_service
