services:
  telegramm_ai_service:
    image: registry.mplab.io/telegramm_ai_service:latest
    networks:
      - web_network
    container_name: telegramm_ai_service
    restart: always
    volumes:
      - /sessions:/app/sessions
    ports:
      - 8088:8089


networks:
  web_network:
    external: true
    name: web_network
