services:
  telegramm_ai_service:
    image: registry.mplab.io/telegramm_ai_service:latest
    container_name: telegramm_ai_service
    restart: always
    volumes:
      - /sessions:/app/sessions
    ports:
      - 8088:8001
  telegramm_send_messages:
    image: registry.mplab.io/telegramm_send_messages:latest
    container_name: telegramm_send_messages
    restart: always
