services:
  telegramm_ai_service:
    image: registry.dplab.tech/telegramm_ai_service:latest
    container_name: telegramm_ai_service
    restart: always
    volumes:
      - /sessions:/app/sessions
    ports:
      - 8088:8001
    env_file: .env-dev
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450